export const ActionTypes = {
    PLUS: 'PLUS',
    MINUS: 'MINUS',
    ADD_TO_LIST: 'ADD_TO_LIST',
    REQ_HOLIDAYS: 'REQ_HOLIDAYS',
    REQ_HOLIDAYS_SUCCESS: 'REQ_HOLIDAYS_SUCCESS',
    REQ_HOLIDAYS_FAILURE: 'REQ_HOLIDAYS_FAILURE',
    DISPOSE_TODO: 'DISPOSE_TODO',
    DISPOSE_ALL_TODOS: 'DISPOSE_ALL_TODOS',
};

